version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install     # Install project dependencies
  build:
    commands:
      - npm run build   # Build the React project
  post_build:
    commands:
      aws s3 cp --recursive ./build s3://codepipeline-us-east-1-525635116198/ReactNodeJS_Pipeline/SourceArti/NUARw3t

