version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install     # Install project dependencies
  build:
    commands:
      - npm run build   # Build the React project
